### ISSUE TITLE
Different value of the goodness-of-fit parameter "Γ" obtained for example 1

### ISSUE THREAD

**Issue by Polsin07** [wollmich/metas-b-least#5]
Hello Sir and thanks for this repository.

The value for "goodness-of-fit" parameter calculated in [Example 1](https://github.com/wollmich/metas-b-least/blob/main/metas_b_least/Example_B_LEAST_1.ipynb) for linear function is different than calculated in [ISO 6143:2001](https://www.iso.org/standard/24665.html).

The last two parameters of the result in Example 1 says:

```markdown
Residual
0.6743048567393399
Maximum absolute value of weighted deviations
0.6309181102471252
```

The norm says in apendix B.2.1, step H.

![image](https://github.com/user-attachments/assets/4cf2da2c-7c66-489e-8baa-3fd6df0b8f25)

> It says that the value for **goodness-of-fit** (maximum absolute value of weighted deviations) is **0,568** compared to **0.6309** from the **Example 1**. Although the value of Sres or residual is equal in both results, **0.6743**.

In this case the difference may be small for parameter "goodness-of-fit". But for values ​​close to the limit Γ <= 2 ([Section 5.2.2](https://www.iso.org/standard/24665.html)) this difference may be significant to validate the order of the equation to be chosen.

**Comment by wollmich** [comment]
The output of the original Power Basic program is:

```
The calibration data set is:

4.500E+00    4.500E-02    1.969E-01    3.938E-03
  1.875E+01    1.875E-01    7.874E-01    1.575E-02
  5.000E+01    5.000E-01    2.023E+00    4.046E-02
Fit type: x vs y

Calibration: Linear case

Ordinary-least-squares results:
b0            b1            u  (b0)       u  (b1)       cov:
-6.1921E-01    2.4977E+01    3.5512E-01    2.8220E-01   -7.9828E-02

Results of ISO 6143 method:
b0            b1            u  (b0)       u  (b1)       cov:
-3.5747E-01    2.4612E+01    1.5716E-01    4.8048E-01   -5.6921E-02

Remaining SSD is:          0.6743
Weighted distances:
   #          x-value    x-dist.    y-dist.
1.00E+00   4.50E+00   4.52E-02  -9.73E-02
  2.00E+00   1.88E+01  -2.75E-01   5.68E-01
  3.00E+00   5.00E+01   2.31E-01  -4.60E-01
Goodness-of-fit measure:   0.5679



##Parameter set##
1 ,-.357466306744814 , 24.6115171860173 , .157156165081977 , 
.480477033820709 ,-5.69207519307518E-2 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0
##End set##

```

So it seems that the reported **goodness-of-fit** is the maximum absolute value of the weighted x or y deviations.

In my case the **reported maximum absolute value of weighted deviations** is the maximum of the weighted $\sqrt{x^2+y^2}$ deviations.

If needed I can change that.

**Comment by wollmich** [comment]
The output of [Example1](https://github.com/wollmich/metas-b-least/blob/objective_func_xy/metas_b_least/Example_B_LEAST_1.ipynb) would be:

```
Residual
0.6743048567393346
Maximum absolute value of weighted deviations
0.5679496652356009
```

**Comment by Polsin07** [comment]
It is definitely done, now the two different approaches to the maximum absolute value of weighted deviations are clearer.

Thanks Sir.

**Comment by wollmich** [comment]
In that case I'll merge the following pull request https://github.com/wollmich/metas-b-least/pull/6.

Then my reported maximum absolute value of weighted deviations will be the same like in the original Power Basic program and the ISO norm.
